services:
  state.search.rabbitmq:
    container_name: state_search_rabbitmq
    image: rabbitmq:3-management
    hostname: state.search.queue
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq 
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: teste1234

  state.persistence.minio:
    image: minio/minio:latest
    container_name: state.persistence.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: teste1234
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # state.search.webapi:
  #   container_name: state_search_webapi
  #   image: ${DOCKER_REGISTRY-}state_search_webapi
  #   build:
  #     context: .
  #     dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080 
  #     - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  rabbitmq_data:
  rabbitmq_log:
  minio_data: